### ISSUE TITLE
file path

### ISSUE THREAD

**Issue by RezaErfani67** [Teal/H2Server#1]
how can i serve file in a directory?

i have index.html in {dist} folder...
i dont know how can i address to this file...

**Comment by xuld** [comment]
The simplest way is changing current directory to `dist` first:
```
cd dist
h2server
```
then you can visit index.html using `http://localhost:8193/index.html`

Do you mean the `auto index` feature?

`h2server --index index.html` will use index.html as default page of directory, visit http://localhost:8193/ will auto address to index.html if it exists.

**Comment by RezaErfani67** [comment]
thank you for fast reply :)
my program (app.js) run from parent directory...
i want address to {dist} folder from upper directory in {app.js}...


about {h2server --index index.html}
oh this param not exists in your document ... excellent

**Comment by xuld** [comment]
Well, `h2server --cwd dist --index index.html` is what you want.
Type `h2server -?` will list all supported options with document.

**Comment by RezaErfani67** [comment]
yesss...
God bless you Dear @xuld
